name: Deploy to Cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dbstjql1/musicdrive
          stage: main
          yaml: |
            name: musicdrive
            app: node
            options:
              nodeversion: 18
              start: npm start
              env:
                - name: SUPABASE_URL
                  value: https://onsxodfsmobsulrsdvwx.supabase.co
                - name: SUPABASE_SERVICE_ROLE_KEY
                  secret: SUPABASE_SERVICE_ROLE_KEY
                - name: ADMIN_PASSWORD
                  secret: ADMIN_PASSWORD
            context:
              git:
                url: https://github.com/${{ github.repository }}.git
                ref: main
                path: backend
