name: Deploy to Cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: dbstjql1-hue/musicdrive
          stage: main
          yaml: |
            name: musicdrive-backend
            app: node
            options:
              nodeversion: 18
              start: npm start
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: main
                path: backend
